name: Test and Release

env:
  # Keep in sync with .changeset/config.json:baseBranch
  MAIN_REF: refs/heads/main

on:
  push:
    branches: ["**"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

# Publish to npm with OIDC
permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test-and-release:
    name: Test and Release
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Wait until postgres is ready before test steps run.
        # See https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # for npx publish
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build package
        run: bun run build

      - name: Test package
        run: bun test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost

      - name: Capture new release versions
        if: ${{ github.ref == env.MAIN_REF }}
        run: |
          if bunx @changesets/cli status --output=release.json; then
            echo "RELEASE=Version $(jq -r '.releases[0].newVersion' release.json)" >> "$GITHUB_ENV"
            rm release.json
          fi

      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == env.MAIN_REF }}
        uses: changesets/action@v1
        with:
          publish: npx changeset publish
          title: ${{ env.RELEASE }}
          commit: ${{ env.RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
